pipeline {
  agent any
  stages {
    stage ('Initialize') {
      steps {
        echo "Placeholder"
      }
    }

    stage ('dockerization-test') {
      steps {
        echo 'test Dockerfile-dry run'
      }
    }

    stage ('build-dockerization') {
      steps {
        echo 'docker run --name name -p 3000:3000'
      }
    }
  }
}
